config/routes.rb
Wit::Application.routes.draw do
  
  resources :invite_requests

  get "pages/home"
  get "pages/override"
  get "pages/contact"
  get "pages/ubuntu"
  get "pages/fedora"

  devise_for :users

  root :to => "pages#home"
  

end

app/models/invite_request.rb
class InviteRequest < ActiveRecord::Base
  validates_presence_of :email
  validates_uniqueness_of :email
  
  attr_accessible :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/invite_requests_controller.rb
class InviteRequestsController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!
  
  def home
  end

  def override
  end

  def contact
  end
  
  def ubuntu
  end

  def fedora
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invite_requests_helper.rb
module InviteRequestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/invite_requests/_form.html.haml
= form_for @invite_request do |f|
  -if @invite_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invite_request.errors.count, "error")} prohibited this invite_request from being saved:"
      %ul
        - @invite_request.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/invite_requests/edit.html.haml
%h1 Editing invite_request

= render 'form'

= link_to 'Show', @invite_request
\|
= link_to 'Back', invite_requests_path

app/views/invite_requests/index.html.haml
%h1 Listing invite_requests

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @invite_requests.each do |invite_request|
    %tr
      %td= invite_request.email
      %td= link_to 'Show', invite_request
      %td= link_to 'Edit', edit_invite_request_path(invite_request)
      %td= link_to 'Destroy', invite_request, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Invite request', new_invite_request_path

app/views/invite_requests/new.html.haml
%h1 Welcome to Wit
%p
%p We are in super secret stealth mode and looking for a few great alpha users.
%p
%p Give us your email address and we'll hook you up with an invite as soon as we can.

= render 'form'

= link_to 'Back', invite_requests_path

app/views/invite_requests/show.html.haml
%h1 Thanks for requesting an invite!
%p We're looking forward to getting you an invite as soon as we can.

%p#notice= notice

%p
  %b Email:
  = @invite_request.email

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
		<div class="brand">
			<%= link_to "Wit", root_path %>
		</div>
          <div class="nav-collapse">
            <ul class="nav">
			  <% if user_signed_in? %>
			  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
			  <% else %>
			    <li><%= link_to "Sign up", new_user_registration_path %></li>
				<li><%= link_to "Sign in", new_user_session_path %></li>
			  <% end %>
				<li><%= link_to "Contact", pages_contact_path %></li>		
            </ul>
        </div>
      </div>
    </div>
  </div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/fedora.html.erb
<div id="noVNC_infotext">
  <p>You can connect to your Droplet's console using our HTML5 in-browser viewer.</p>
</div>
<div id="noVNC_click_me" class="btn">
  Connect
</div>
<%  %>
<div id="noVNC_screen">
  <div id="noVNC_status_bar" class="noVNC_status_bar">
      <table border=0 width="100%"><tr>
          <td><div id="noVNC_status" style="display:none;">Loading</div></td>
          <td width="1%"><div id="noVNC_buttons">
              <input type=button value="Send CtrlAltDel" id="sendCtrlAltDelButton" style="display:none;">
                  </div></td>
      </tr></table>
  </div>
  <canvas id="noVNC_canvas" width="620px" height="5px">
      Canvas not supported.
  </canvas>
</div>
<script>
/*jslint white: false */
/*global window, $, Util, RFB, */
"use strict";

var rfb;

function passwordRequired(rfb) {
    var msg;
    msg = '<form onsubmit="return setPassword();"';
    msg += '  style="margin-bottom: 0px">';
    msg += 'Password Required: ';
    msg += '<input type=password size=10 id="password_input" class="noVNC_status">';
    msg += '<\/form>';
    $D('noVNC_status_bar').setAttribute("class", "noVNC_status_warn");
    $D('noVNC_status').innerHTML = msg;
}
function setPassword() {
    rfb.sendPassword($D('password_input').value);
    return false;
}
function sendCtrlAltDel() {
    rfb.sendCtrlAltDel();
    return false;
}
function updateState(rfb, state, oldstate, msg) {
    var s, sb, cad, level;
    s = $D('noVNC_status');
    sb = $D('noVNC_status_bar');
    cad = $D('sendCtrlAltDelButton');
    switch (state) {
        case 'failed':       level = "error";  break;
        case 'fatal':        level = "error";  break;
        case 'normal':       level = "normal"; break;
        case 'disconnected': level = "normal"; break;
        case 'loaded':       level = "normal"; break;
        default:             level = "warn";   break;
    }

    if (state === "normal") { cad.disabled = false; }
    else                    { cad.disabled = true; }

    if (typeof(msg) !== 'undefined') {
        sb.setAttribute("class", "noVNC_status_" + level);
        s.innerHTML = msg;
    }
}

$('#noVNC_click_me').click(function () {
    var host, port, password, path;

    $('#noVNC_click_me').hide();
    $('#noVNC_infotext').hide();

    host = '69.55.54.2';
    port = '6085';
    password = WebUtil.getQueryVar('password', 'nYOxe5kN');
    path = WebUtil.getQueryVar('path', '');
    if ((!host) || (!port)) {
        updateState('failed',
            "Must specify host and port in URL");
        return;
    }

    rfb = new RFB({'target':       $D('noVNC_canvas'),
                   'encrypt':      WebUtil.getQueryVar('encrypt', false),
                   'true_color':   WebUtil.getQueryVar('true_color', true),
                   'local_cursor': WebUtil.getQueryVar('cursor', true),
                   'shared':       WebUtil.getQueryVar('shared', true),
                   'view_only':    WebUtil.getQueryVar('view_only', false),
                   'updateState':  updateState,
                   'onPasswordRequired':  passwordRequired});
    rfb.connect(host, port, password, path);

    setTimeout('resize_modal()',1500);

});

function resize_modal() {
  var new_height = $('#noVNC_canvas').attr('height');
  var new_width = $('#noVNC_canvas').attr('width');
  new_height = parseFloat(new_height);
  new_width = parseFloat(new_width);
  new_height = new_height + 20;
  new_width = new_width + 20;
  
  $('.vnc .modal-body').css('max-height', new_height);
  $('.vnc .modal-body').css('max-width', new_width);
  $('.vnc .modal-body').css('width', new_width);
  $('.vnc').css('max-height', new_height + 130);
  $('.vnc').css('max-width', new_width + 30);
  $('.vnc').css('width', new_width + 30);
  $('.vnc .modal-body').css('background', '#000');
  //$('.vnc.modal').css('left', '40%');
  //$('.vnc.modal.fade.in').css('top', '25%');
  //modal = $('.vnc');
  //modal.css('margin-top',(modal.outerHeight()/2)*-1);
  //modal.css('margin-left',(modal.outerWidth()/2)*-1);
  
  $('.vnc').css('margin-top',((new_height+130)/2)*-1);
  $('.vnc').css('margin-left',((new_width+130)/2)*-1);
  $('.vnc').css('max-height', new_height + 130);
  $('.vnc').css('max-width', new_width + 30);
  $('.vnc').css('width', new_width + 30);
  $('.vnc').css('height', new_height + 130);
  $('.vnc .modal-body').css('max-height', new_height);
  $('.vnc .modal-body').css('max-width', new_width);
  $('.vnc .modal-body').css('width', new_width-10);
  $('.vnc .modal-body').css('height', new_height-10);
  $('.vnc .modal-body').css('margin', '0 auto');
}

</script>

app/views/pages/home.html.haml
%h1 Welcome to WIT
%p Click on the images below

= link_to image_tag('ubuntu_final.png', :id => 'thumb', :style => "width: 320px;"), "/pages/ubuntu/"
= link_to image_tag('centos.png', :id => 'thumb', :style => "width: 320px;"), "/pages/centos/"
= link_to image_tag('fedora.png', :id => 'thumb', :style => "width: 320px;"), "/pages/fedora/"
%p
= link_to image_tag('gentoo.png', :id => 'thumb', :style => "width: 320px;"), "/pages/gentoo/"
= link_to image_tag('windows.png', :id => 'thumb', :style => "width: 320px;"), "/pages/windows/"

app/views/pages/ubuntu.html.erb
<div id="noVNC_infotext">
  <p>You can connect to your Droplet's console using our HTML5 in-browser viewer.</p>
</div>
<div id="noVNC_click_me" class="btn">
  Connect
</div>
<%  %>
<div id="noVNC_screen">
  <div id="noVNC_status_bar" class="noVNC_status_bar">
      <table border=0 width="100%"><tr>
          <td><div id="noVNC_status" style="display:none;">Loading</div></td>
          <td width="1%"><div id="noVNC_buttons">
              <input type=button value="Send CtrlAltDel" id="sendCtrlAltDelButton" style="display:none;">
                  </div></td>
      </tr></table>
  </div>
  <canvas id="noVNC_canvas" width="620px" height="5px">
      Canvas not supported.
  </canvas>
</div>
<script>
/*jslint white: false */
/*global window, $, Util, RFB, */
"use strict";

var rfb;

function passwordRequired(rfb) {
    var msg;
    msg = '<form onsubmit="return setPassword();"';
    msg += '  style="margin-bottom: 0px">';
    msg += 'Password Required: ';
    msg += '<input type=password size=10 id="password_input" class="noVNC_status">';
    msg += '<\/form>';
    $D('noVNC_status_bar').setAttribute("class", "noVNC_status_warn");
    $D('noVNC_status').innerHTML = msg;
}
function setPassword() {
    rfb.sendPassword($D('password_input').value);
    return false;
}
function sendCtrlAltDel() {
    rfb.sendCtrlAltDel();
    return false;
}
function updateState(rfb, state, oldstate, msg) {
    var s, sb, cad, level;
    s = $D('noVNC_status');
    sb = $D('noVNC_status_bar');
    cad = $D('sendCtrlAltDelButton');
    switch (state) {
        case 'failed':       level = "error";  break;
        case 'fatal':        level = "error";  break;
        case 'normal':       level = "normal"; break;
        case 'disconnected': level = "normal"; break;
        case 'loaded':       level = "normal"; break;
        default:             level = "warn";   break;
    }

    if (state === "normal") { cad.disabled = false; }
    else                    { cad.disabled = true; }

    if (typeof(msg) !== 'undefined') {
        sb.setAttribute("class", "noVNC_status_" + level);
        s.innerHTML = msg;
    }
}

$('#noVNC_click_me').click(function () {
    var host, port, password, path;

    $('#noVNC_click_me').hide();
    $('#noVNC_infotext').hide();

    host = '69.55.54.2';
    port = '6085';
    password = WebUtil.getQueryVar('password', 'nYOxe5kN');
    path = WebUtil.getQueryVar('path', '');
    if ((!host) || (!port)) {
        updateState('failed',
            "Must specify host and port in URL");
        return;
    }

    rfb = new RFB({'target':       $D('noVNC_canvas'),
                   'encrypt':      WebUtil.getQueryVar('encrypt', false),
                   'true_color':   WebUtil.getQueryVar('true_color', true),
                   'local_cursor': WebUtil.getQueryVar('cursor', true),
                   'shared':       WebUtil.getQueryVar('shared', true),
                   'view_only':    WebUtil.getQueryVar('view_only', false),
                   'updateState':  updateState,
                   'onPasswordRequired':  passwordRequired});
    rfb.connect(host, port, password, path);

    setTimeout('resize_modal()',1500);

});

function resize_modal() {
  var new_height = $('#noVNC_canvas').attr('height');
  var new_width = $('#noVNC_canvas').attr('width');
  new_height = parseFloat(new_height);
  new_width = parseFloat(new_width);
  new_height = new_height + 20;
  new_width = new_width + 20;
  
  $('.vnc .modal-body').css('max-height', new_height);
  $('.vnc .modal-body').css('max-width', new_width);
  $('.vnc .modal-body').css('width', new_width);
  $('.vnc').css('max-height', new_height + 130);
  $('.vnc').css('max-width', new_width + 30);
  $('.vnc').css('width', new_width + 30);
  $('.vnc .modal-body').css('background', '#000');
  //$('.vnc.modal').css('left', '40%');
  //$('.vnc.modal.fade.in').css('top', '25%');
  //modal = $('.vnc');
  //modal.css('margin-top',(modal.outerHeight()/2)*-1);
  //modal.css('margin-left',(modal.outerWidth()/2)*-1);
  
  $('.vnc').css('margin-top',((new_height+130)/2)*-1);
  $('.vnc').css('margin-left',((new_width+130)/2)*-1);
  $('.vnc').css('max-height', new_height + 130);
  $('.vnc').css('max-width', new_width + 30);
  $('.vnc').css('width', new_width + 30);
  $('.vnc').css('height', new_height + 130);
  $('.vnc .modal-body').css('max-height', new_height);
  $('.vnc .modal-body').css('max-width', new_width);
  $('.vnc .modal-body').css('width', new_width-10);
  $('.vnc .modal-body').css('height', new_height-10);
  $('.vnc .modal-body').css('margin', '0 auto');
}

</script>